# --- Frontend bucket -----------------------------------------------------------
# Serves the built React app. Private bucket — CloudFront accesses it via
# Origin Access Control (OAC), nothing is public directly on S3 itself.

resource "aws_s3_bucket" "frontend" {
  bucket = "${var.name_prefix}-frontend-${data.aws_caller_identity.current.account_id}"

  tags = {
    Project = "Cloud Architecture Platform"
    Purpose = "frontend-hosting"
  }
}

resource "aws_s3_bucket_public_access_block" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_website_configuration" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  index_document {
    suffix = "index.html"
  }

  # SPA fallback: this app doesn't use path-based routing (confirmed — no
  # react-router, navigation is all internal component state), so this is
  # mostly a safety net rather than a hard requirement.
  error_document {
    key = "index.html"
  }
}

resource "aws_s3_bucket_policy" "frontend" {
  bucket = aws_s3_bucket.frontend.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AllowCloudFrontOAC"
      Effect    = "Allow"
      Principal = { Service = "cloudfront.amazonaws.com" }
      Action    = "s3:GetObject"
      Resource  = "${aws_s3_bucket.frontend.arn}/*"
      Condition = {
        StringEquals = {
          "AWS:SourceArn" = aws_cloudfront_distribution.frontend.arn
        }
      }
    }]
  })
}

# --- User content bucket --------------------------------------------------------
# Avatars, diagram exports/thumbnails. Fully private — the ONLY access path
# is presigned URLs generated by the Lambda functions, never direct public
# reads. This is the bucket that actually holds per-user data.

resource "aws_s3_bucket" "user_content" {
  bucket = "${var.name_prefix}-user-content-${data.aws_caller_identity.current.account_id}"

  tags = {
    Project = "Cloud Architecture Platform"
    Purpose = "user-content"
  }
}

resource "aws_s3_bucket_public_access_block" "user_content" {
  bucket = aws_s3_bucket.user_content.id

  # ACLs stay fully blocked — nothing here uses them. block_public_policy and
  # restrict_public_buckets are relaxed so the bucket policy below can grant
  # public read on thumbnails/ and avatars/ specifically. Everything else
  # (exports/) stays private, reachable only via the presigned URLs the
  # Lambda functions generate.
  block_public_acls       = true
  block_public_policy     = false
  ignore_public_acls      = true
  restrict_public_buckets = false
}

resource "aws_s3_bucket_policy" "user_content_public_read" {
  bucket = aws_s3_bucket.user_content.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "PublicReadThumbnailsAndAvatars"
      Effect    = "Allow"
      Principal = "*"
      Action    = "s3:GetObject"
      Resource = [
        "${aws_s3_bucket.user_content.arn}/thumbnails/*",
        "${aws_s3_bucket.user_content.arn}/avatars/*",
      ]
    }]
  })

  depends_on = [aws_s3_bucket_public_access_block.user_content]
}

resource "aws_s3_bucket_cors_configuration" "user_content" {
  bucket = aws_s3_bucket.user_content.id

  cors_rule {
    allowed_methods = ["GET", "PUT", "POST"]
    allowed_origins = [var.frontend_url, "http://localhost:3000"]
    allowed_headers = ["*"]
    max_age_seconds = 3000
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "user_content" {
  bucket = aws_s3_bucket.user_content.id

  rule {
    id     = "expire-old-versions"
    status = "Enabled"
    filter {} # empty filter = applies to every object in the bucket
    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}
