# --- Aurora master credentials --------------------------------------------------
# Password is randomly generated by Terraform and stored only in Secrets
# Manager — never appears in the .tf files or plan output in plaintext.

resource "random_password" "db_master" {
  length  = 24
  special = false # Data API + some client libraries mishandle certain special chars; alnum is plenty of entropy at this length
}

resource "aws_secretsmanager_secret" "db_master" {
  name        = "${var.name_prefix}/aurora/master-credentials"
  description = "Aurora Serverless v2 master credentials - referenced by the RDS Data API and Lambda functions"

  tags = {
    Project = "Cloud Architecture Platform"
  }
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({
    username = var.db_master_username
    password = random_password.db_master.result
  })
}
